# Part 2 - baseline model performance

## Import libraries 

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd

from src import *

## Loading data

In [2]:
dataloader = CSVDataLoader('data/MSFT_2006-01-01_to_2018-01-01.csv')
raw_df = dataloader.load()

print(raw_df.info())
print()
print(raw_df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3019 entries, 0 to 3018
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    3019 non-null   object 
 1   Open    3019 non-null   float64
 2   High    3019 non-null   float64
 3   Low     3019 non-null   float64
 4   Close   3019 non-null   float64
 5   Volume  3019 non-null   int64  
 6   Name    3019 non-null   object 
dtypes: float64(4), int64(1), object(2)
memory usage: 165.2+ KB
None

         Date   Open   High    Low  Close     Volume  Name
0  2006-01-03  26.25  27.00  26.10  26.84   79974418  MSFT
1  2006-01-04  26.77  27.08  26.77  26.97   57975661  MSFT
2  2006-01-05  26.96  27.13  26.91  26.99   48247610  MSFT
3  2006-01-06  26.89  27.00  26.49  26.91  100969092  MSFT
4  2006-01-09  26.93  27.07  26.76  26.86   55627836  MSFT


## Create datasets

In [5]:
X_train_1, y_train_1, X_test_1, y_test_1 = dataloader.split_by_year([2006, 2007], [2008])

print(X_train_1.shape)
print(X_train_1[:4, :])

(502, 4)
[[2.62500000e+01 2.70000000e+01 2.61000000e+01 7.99744180e+07]
 [2.67700000e+01 2.70800000e+01 2.67700000e+01 5.79756610e+07]
 [2.69600000e+01 2.71300000e+01 2.69100000e+01 4.82476100e+07]
 [2.68900000e+01 2.70000000e+01 2.64900000e+01 1.00969092e+08]]
